#!/usr/bin/env sh

alt - q : ~/.local/bin/new-wezterm
alt - b : open -a "Zen"
alt - c : open -na "Visual Studio Code"
alt - s : open -a "Spotify"
cmd - return : open -a "Finder"

alt - left : yabai -m window --focus west
alt - down : yabai -m window --focus south
alt - up : yabai -m window --focus north
alt - right : yabai -m window --focus east
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

shift + alt - left : ~/.config/skhd/scripts/smart-swap.py west
shift + alt - right : ~/.config/skhd/scripts/smart-swap.py east
shift + alt - up : ~/.config/skhd/scripts/smart-swap.py north
shift + alt - down : ~/.config/skhd/scripts/smart-swap.py south
shift + alt - h : ~/.config/skhd/scripts/smart-swap.py west
shift + alt - l : ~/.config/skhd/scripts/smart-swap.py east
shift + alt - k : ~/.config/skhd/scripts/smart-swap.py north
shift + alt - j : ~/.config/skhd/scripts/smart-swap.py south

ctrl - h : skhd -k "ctrl - left"
ctrl - l : skhd -k "ctrl - right"

shift + ctrl - left : yabai -m window --space prev; yabai -m space --focus prev
shift + ctrl - right : yabai -m window --space next; yabai -m space --focus next
shift + ctrl - h : yabai -m window --space prev; yabai -m space --focus prev
shift + ctrl - l : yabai -m window --space next; yabai -m space --focus next

ctrl + alt - left : ~/.config/skhd/scripts/resize-window.py left
ctrl + alt - down : ~/.config/skhd/scripts/resize-window.py down
ctrl + alt - up : ~/.config/skhd/scripts/resize-window.py up
ctrl + alt - right : ~/.config/skhd/scripts/resize-window.py right
ctrl + alt - h : ~/.config/skhd/scripts/resize-window.py left
ctrl + alt - j : ~/.config/skhd/scripts/resize-window.py down
ctrl + alt - k : ~/.config/skhd/scripts/resize-window.py up
ctrl + alt - l : ~/.config/skhd/scripts/resize-window.py right

ctrl - z : yabai -m window --toggle float && yabai -m window --grid 4:4:1:1:2:2
shift + alt - m : yabai -m window --toggle zoom-fullscreen
alt - o : yabai -m window --toggle split

ctrl + alt - r : yabai -m space --rotate 270
ctrl + alt + shift - r : yabai -m space --rotate 90
ctrl + alt - b : yabai -m space --balance
ctrl + alt - 1 : yabai -m space --layout bsp
ctrl + alt - 2 : yabai -m space --layout stack
ctrl + alt - 3 : yabai -m space --layout float

ctrl + alt + shift - 0 : yabai --restart-service

cmd + shift - t : ~/.config/skhd/scripts/scratchpad.py
